II_TSI_UTFPR_Guarapuava/config/routes.rb
MinicursoRails::Application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :series

  

end

II_TSI_UTFPR_Guarapuava/app/models/series.rb
class Series < ActiveRecord::Base
end

II_TSI_UTFPR_Guarapuava/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

II_TSI_UTFPR_Guarapuava/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

II_TSI_UTFPR_Guarapuava/app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_action :set_series, only: [:show, :edit, :update, :destroy]

  # GET /series
  # GET /series.json
  def index
    @series = Series.all
  end

  # GET /series/1
  # GET /series/1.json
  def show
  end

  # GET /series/new
  def new
    @series = Series.new
  end

  # GET /series/1/edit
  def edit
  end

  # POST /series
  # POST /series.json
  def create
    @series = Series.new(series_params)

    respond_to do |format|
      if @series.save
        format.html { redirect_to @series, notice: 'Series was successfully created.' }
        format.json { render action: 'show', status: :created, location: @series }
      else
        format.html { render action: 'new' }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /series/1
  # PATCH/PUT /series/1.json
  def update
    respond_to do |format|
      if @series.update(series_params)
        format.html { redirect_to @series, notice: 'Series was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /series/1
  # DELETE /series/1.json
  def destroy
    @series.destroy
    respond_to do |format|
      format.html { redirect_to series_index_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_series
      @series = Series.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def series_params
      params.require(:series).permit(:title, :description)
    end
end

II_TSI_UTFPR_Guarapuava/app/helpers/home_helper.rb
module HomeHelper
end

II_TSI_UTFPR_Guarapuava/app/helpers/series_helper.rb
module SeriesHelper
end

II_TSI_UTFPR_Guarapuava/app/views/home/index.html.haml
%h1 Home#index
%p Find me in app/views/home/index.html.haml

II_TSI_UTFPR_Guarapuava/app/views/layouts/application.html.haml
!!!
%html
  %head
    %title MinicursoRails
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    .container
      .well
        = yield

II_TSI_UTFPR_Guarapuava/app/views/series/_form.html.haml
= form_for(@series) do |f|
  - if @series.errors.any?
    #error_explanation
      %h2
        = pluralize(@series.errors.count, "error")
        prohibited this series from being saved:
      %ul
        - @series.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :title
    %br/
    = f.text_field :title
  .field
    = f.label :description
    %br/
    = f.text_area :description
  .actions
    = f.submit

II_TSI_UTFPR_Guarapuava/app/views/series/edit.html.haml
%h1 Editing series
= render 'form'
= link_to 'Show', @series
|
\#{link_to 'Back', series_index_path}

II_TSI_UTFPR_Guarapuava/app/views/series/index.html.haml
%h1 Listing series
%table
  %thead
    %tr
      %th Title
      %th Description
      %th
      %th
      %th
  %tbody
    - @series.each do |series|
      %tr
        %td= series.title
        %td= series.description
        %td= link_to 'Show', series
        %td= link_to 'Edit', edit_series_path(series)
        %td= link_to 'Destroy', series, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Series', new_series_path

II_TSI_UTFPR_Guarapuava/app/views/series/new.html.haml
%h1 New series
= render 'form'
= link_to 'Back', series_index_path

II_TSI_UTFPR_Guarapuava/app/views/series/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @series.title
%p
  %strong Description:
  = @series.description
= link_to 'Edit', edit_series_path(@series)
|
\#{link_to 'Back', series_index_path}